<?php
$this->headTitle("大红包海淘优惠券－海外购物找优惠券找海淘攻略教程首选大红包网站");
$this->headMeta()->appendName("keywords", "海淘,海淘优惠券,海外购物,海淘攻略教程");
$this->headMeta()->appendName("description", "大红包海淘优惠券网站致力于为用户提供及时有效的海外购物优惠券及海淘特价促销信息，并且针对不同的海外商家制订了一对一的海淘购物攻略教程，为中国消费者在网上进行海外购物提供了最为便利的途径。");
?>
<div class="mainleft">
	<!-- 全部优惠券分类 -->
	<?php print $this->partial('us/default/allCategory.phtml');?>
	
	<!-- 海淘攻略 && 优惠券使用攻略 -->
	<?php print $this->partial('us/default/siteHelp.phtml');?>
	
	<!-- 邮箱订阅 -->
	<?php print $this->partial('us/default/emailSubcription.phtml');?>

	<!-- 帮助中心 -->
	<?php print $this->partial('us/default/helpCenter.phtml');?>

	<!-- 特价促销 -->
	<?php print $this->partial('us/default/specialDealsList.phtml');?>

	<!-- google ads -->
	<?php print $this->partial('us/default/googleAdsList.phtml');?>
</div>
<div class="mainright">
	<!-- 热门商家 -->
	<?php print $this->partial('us/default/hotMerchantList.phtml');?>

	<!-- 热门优惠券 -->
	<?php if ($this->couponList):?>
	<div class="couponlistwp">
		<div class="headline">
			<a href="<?php print $couponMore; ?>" class="seemore">更多&gt;&gt;</a>
			<h2>热门优惠券</h2>
		</div>
		<?php print $this->partial('us/default/couponList.phtml');?>
	</div>
	<?php endif;?>
</div>