<?php
/**
* save.phtml
*-------------------------
*
* 
*
* PHP versions 5
*
* LICENSE: This source file is from Smarter Ver2.0, which is a comprehensive shopping engine 
* that helps consumers to make smarter buying decisions online. We empower consumers to compare 
* the attributes of over one million products in the common channels and common categories
* and to read user product reviews in order to make informed purchase decisions. Consumers can then 
* research the latest promotional and pricing information on products listed at a wide selection of 
* online merchants, and read user reviews on those merchants.
* The copyrights is reserved by http://www.mezimedia.com. 
* Copyright (c) 2006, Mezimedia. All rights reserved.
*
* @author Yaron Jiang <yjiang@corp.valueclick.com.cn>
* @copyright (C) 2004-2013 Mezimedia.com
* @license http://www.mezimedia.com PHP License 5.0
* @version CVS: $Id: save.phtml,v 1.2 2013/04/17 06:45:05 yjiang Exp $
* @link http://www.dahongbao.com/
* @deprecated File deprecated in Release 3.0.0
*/
use Custom\Util\Utilities;
$form = $this->form;
?>

<div class="box">
<div class="box-header">
<h2><a class="btn btn-inverse" href="<?php echo Utilities::decode($this->referer)?>">返回上一页</a>
<i class="icon-box"></i>编辑位置</h2>
</div>

<div class="box-content">
<form class="box-form" action="<?php $this->url(null , array('controller' => 'recommendType' , 'action' => 'save'))
?>?referer=<?php echo $this->referer?>" method="post">
<?php echo $this->formSelect($form->get('SiteID'))?>
<?php echo $this->formHidden($form->get('RecommendTypeID'))?>
<?php echo $this->formSelect($form->get('ContentType'))?>
<?php echo $this->formText($form->get('RecommendTypeName'))?>
<?php echo $this->formText($form->get('RecommendTypeEnName'))?>
<?php echo $this->formSubmit($form->get('submit') , '提交')?>
</form>
</div>
</div>
