<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<?php echo $this->headTitle();?>
<?php echo $this->headMeta(); ?>
<?php 
echo $this->headLink(
    array(
        'rel' => 'shortcut icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    )
)
->prependStylesheet($this->basePath() . '/styles/CN/global.css');
?>
<!--[if IE 6]>
<link href="/styles/CN/ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js') ?>
<script><?php echo "var __USER_DOMAIN = '".$this->siteConfg['__USER_DOMAIN']."';";?></script>
<script language="javascript" type="text/javascript" src="<?php print $siteConfg['__USER_DOMAIN']; ?>/auth/userinfo"></script>
<script language="javascript" type="text/javascript" src="<?php print $this->basePath(); ?>/js/common.js"></script>
<script language="javascript" type="text/javascript" src="<?php print $this->basePath(); ?>/js/cn.js"></script>
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?19bbc4aab5de3a18739550f2a6d0cc0b";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
</head>
<body>
	<?php print $this->partial('front-end/default/header.phtml'); ?>
	<?php echo $this->content; ?>
	<?php print $this->partial('front-end/default/footer.phtml'); ?>
</body>
</html>