<?php if ($this->dealsList):?>
<div class="articleBox">
	<?php foreach ($this->dealsList as $key => $deals):?>
	<div class="post<?php if (count($this->dealsList) != $key + 1):?> line<?php endif;?>">
		<h3><a href="<?php print $deals['DealsdetailUrl'];?>" target="_blank">【<?php print $deals['MerchantName'];?>】<?php print strip_tags($deals['CouponName']);?></a></h3>
		<?php if ($deals['InsertDateTime']):?>
		<p class="date"><?php print date('Y-m-d', strtotime($deals['InsertDateTime']));?></p>
		<?php endif;?>
		<?php if ($deals['CouponDescription']):?>
		<p><?php print $deals['CouponDescription'];?></p>
		<?php endif;?>
		<div class="button">
			<ul>
				<li class="buy"><a href="javascript:;" onmouseup="redirectLink('<?php print $deals['OfferUrl'];?>', this)" target="_blank">直接购买</a></li>
			</ul>
		</div>
	</div>
	<?php endforeach;?>
</div>
<?php endif;?>