<div class="footerInfoBg">
    <div class="footerInfo">
         <div class="col">
              <h3>新手帮助</h3>
              <ul>
                 <li><a target="_blank" href="/article-5/">什么是大红包优惠券</a></li>
                 <li><a target="_blank" href="/article-7/">如何领取优惠券</a></li>
                 <li><a target="_blank" href="/article-8/">如何使用优惠券</a></li>
              </ul>
         </div>
         <div class="col">
              <h3>意见反馈</h3>
              <ul>
                 <li><a target="_blank" href="<?php print $this->siteConfg['__USER_DOMAIN']."/privatemsg/write?title=tousu";?>">将意见反馈给大红包</a></li>
                 <li><a target="_blank" href="<?php print $this->siteConfg['__USER_DOMAIN']."/privatemsg/write?title=tousu";?>">投诉中心</a></li>
              </ul>
         </div> 
         <div class="col">
              <h3>公司信息</h3>
              <ul>
                 <li><a target="_blank" href="/article-9/">关于大红包</a></li>
                 <li><a target="_blank" href="/article-10/">联系我们</a></li>
              </ul>
         </div>
         <div class="iconLinks">
             <ul>
                <li class="help"><a target="_blank" href="/help/">帮助中心</a></li>
                <li class="suggest"><a target="_blank" href="<?php print $this->siteConfg['__USER_DOMAIN']."/privatemsg/write?title=tousu";?>">意见反馈</a></li>
                <li class="subscription"><a target="_blank" href="/article-11/">订阅优惠券</a></li>
             </ul> 
         </div>
         <div class="cl"></div>    
    </div>
</div>
<!-- end footerInfoBg-->
<div class="footer">
     <div class="footerLink">
        <a target="_blank" href="/article-9/">关于大红包</a>  |  <a target="_blank" href="/article-13/">免责声明</a>  |  <a target="_blank" href="/article-14/">隐私声明</a>  |  <a target="_blank" href="/article-12/">使用条件</a>  |  <a target="_blank" href="/article-10/">联系我们</a>  
     </div>
     <div class="address"><span>版权归 &copy; <?php print date('Y');?> 上海惠可网络技术有限公司所有</span>    <span><a href="/">www.dahongbao.com</a></span>    <span><a href="http://www.miibeian.gov.cn/" target="_blank" style="color:#666666">沪ICP备12034406号</a></span> </div>
</div>
<div class="gototop disn"><a href="#"><span>返回顶部<b></b></span></a></div>
<script language="javascript" type="text/javascript" src="<?php print $this->basePath(); ?>/js/tracker.js"></script>
<script type="text/javascript">
var sessionId = '<?php print $this->sessionId;?>';
var requestId = '<?php print $this->requestId;?>';
track(requestId, sessionId);
</script>