<div class="merchantinfo">
	<div class="content clearfix">
		<div class="coll">
			<div class="imgbox"><a href="javascript:;" onmouseup="redirectLink('<?php print $merchantInfo['MerchantOfferUrl'];?>', this)" target="_blank"><img src="<?php print __IMAGE_DOMAIN_NAME."".$merchantInfo['LogoFile'];?>" /></a></div>
			<div class="mname"><a href="javascript:;" onmouseup="redirectLink('<?php print $merchantInfo['MerchantOfferUrl'];?>', this)" target="_blank"><?php print $merchantInfo['MerchantName'];?></a></div>
			<div class="gotostore"><a href="javascript:;" onmouseup="redirectLink('<?php print $merchantInfo['MerchantOfferUrl'];?>', this)" target="_blank" class="btn"><span>直接购买</span></a></div>
			<p>&nbsp;</p>
		</div>
		<div class="merchantcol">
			<?php if ($merchantInfo['DescriptionCNShort']):?>
			<p><?php print $merchantInfo['DescriptionCNShort'];?><?php if ($merchantInfo['DescriptionCN'] != $merchantInfo['DescriptionCNShort']):?>&nbsp;&nbsp;<a class="unfold" href="#">更多&gt;&gt;</a><?php endif;?></p>
			<?php if ($merchantInfo['DescriptionCN'] != $merchantInfo['DescriptionCNShort']):?>
			<p class="disn"><?php print $merchantInfo['DescriptionCN'];?>&nbsp;&nbsp;<a class="fold" href="#">收起&gt;&gt;</a></p>
			<?php endif;?>
			<?php endif;?>
			<ul>
				<?php if ($merchantInfo['MainSales']):?><li><strong>主营业务：</strong><?php print $merchantInfo['MainSales'];?></li><?php endif;?>
				<?php if ($merchantInfo['SupportDeliveryCN'] == 'YES' || $merchantInfo['SupportCN'] == 'YES'):?>
				<li>
				<?php if ($merchantInfo['SupportDeliveryCN'] == 'YES'):?><a href="#" class="deliver">支持直邮</a><?php endif;?>
				<?php if ($merchantInfo['SupportCN'] == 'YES'):?><a href="#" class="language">支持中文</a><?php endif;?>	
				</li>
				<?php endif;?>
				<?php if ($merchantInfo['Payment']):?>
				<li>
				<?php foreach ($merchantInfo['Payment'] as $patment):?>
				<img src="<?php print __IMAGE_DOMAIN_NAME;?>/img/merchant/payment/<?php print $patment;?>.png">
				<?php endforeach;?>
				</li>
				<?php endif;?>
			</ul>
		</div>
	</div>
</div>