<?php
/**
* addAllow.phtml
*-------------------------
*
* 
*
* PHP versions 5
*
* LICENSE: This source file is from Smarter Ver2.0, which is a comprehensive shopping engine 
* that helps consumers to make smarter buying decisions online. We empower consumers to compare 
* the attributes of over one million products in the common channels and common categories
* and to read user product reviews in order to make informed purchase decisions. Consumers can then 
* research the latest promotional and pricing information on products listed at a wide selection of 
* online merchants, and read user reviews on those merchants.
* The copyrights is reserved by http://www.mezimedia.com. 
* Copyright (c) 2006, Mezimedia. All rights reserved.
*
* @author Yaron Jiang <yjiang@corp.valueclick.com.cn>
* @copyright (C) 2004-2013 Mezimedia.com
* @license http://www.mezimedia.com PHP License 5.0
* @version CVS: $Id: allow.phtml,v 1.2 2013/04/18 14:13:04 yjiang Exp $
* @link http://www.dahongbao.com/
* @deprecated File deprecated in Release 3.0.0
*/
$form = $this->form;
$this->headLink()->appendStylesheet($this->basePath('styles/BackEnd/allow.css'))
?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i><?php echo $this->role?>权限管理</h2>
    </div>
    
    <div class="box-content">
        <form action="<?php echo $this->url('backend' , array('controller' => 'acl' , 'action' => 'allow'));?>" method="post">
        <?php echo $this->formHidden($form->get('role'))?>
        <?php if(count($form->get('resources')->getValueOptions()) <= 0):?>
        <p class="input-group">已拥有所有权限</p>
        <?php else:?>
        <?php echo $this->formSelect($form->get('resources'))?>
        <?php endif;?>
        
        <?php if(count($form->get('deresources')->getValueOptions()) <= 0):?>
        <p class="input-group">没有任何权限</p>
        <?php else:?>
        <?php echo $this->formSelect($form->get('deresources'))?>
        <?php endif;?>
        <?php echo $this->formSubmit($form->get('submit') , '提交')?>
        </form>
    </div>
</div>