<?php
/**
* index.phtml
*-------------------------
*
* 
*
* PHP versions 5
*
* LICENSE: This source file is from Smarter Ver2.0, which is a comprehensive shopping engine 
* that helps consumers to make smarter buying decisions online. We empower consumers to compare 
* the attributes of over one million products in the common channels and common categories
* and to read user product reviews in order to make informed purchase decisions. Consumers can then 
* research the latest promotional and pricing information on products listed at a wide selection of 
* online merchants, and read user reviews on those merchants.
* The copyrights is reserved by http://www.mezimedia.com. 
* Copyright (c) 2006, Mezimedia. All rights reserved.
*
* @author Yaron Jiang <yjiang@corp.valueclick.com.cn>
* @copyright (C) 2004-2013 Mezimedia.com
* @license http://www.mezimedia.com PHP License 5.0
* @version CVS: $Id: index.phtml,v 1.1 2013/05/20 02:44:46 yjiang Exp $
* @link http://www.dahongbao.com/
* @deprecated File deprecated in Release 3.0.0
*/

$this->headScript()->appendFile($this->basePath('js/BackEnd/smcn-mer-feed-index.js'));
?>
<div class="box">
<div class="box-header">
<h2><i class="icon-box"></i>聪明点导入商家管理</h2>
</div>

<div class="box-content">
<form class="box-form" action="/SmcnMerFeed/index" method="get">
<div class="input-group">
<select name="type" class="select">
<option value="id">商家ID</option>
<option value="name">商家名</option>
</select>

<input type="text" name="value" />

<button type="submit">搜索</button>
</div>
</form>

<?php if($this->list):?>
<table class="table">
<tr>
<th>ID</th>
<th>商家名</th>
<th>操作</th>
</tr>

<?php foreach($this->list as $val):?>
<tr>
<td><?php echo $val['MerchantID']?></td>
<td><?php echo $val['MerchantName']?></td>
<td><a class="btn btn-primary" href="<?php echo $this->url(null , array('controller' => 'SmcnMerFeed' 
    , 'action' => 'insert'));?>?id=<?php echo $val['MerchantID']?>">导入</a></td>
</tr>
<?php endforeach;?>
</table>
<?php else:?>
<p>没有找到</p>
<?php endif;?>
</div>
</div>