<?php
/**
* save.phtml
*-------------------------
*
* 
*
* PHP versions 5
*
* LICENSE: This source file is from Smarter Ver2.0, which is a comprehensive shopping engine 
* that helps consumers to make smarter buying decisions online. We empower consumers to compare 
* the attributes of over one million products in the common channels and common categories
* and to read user product reviews in order to make informed purchase decisions. Consumers can then 
* research the latest promotional and pricing information on products listed at a wide selection of 
* online merchants, and read user reviews on those merchants.
* The copyrights is reserved by http://www.mezimedia.com. 
* Copyright (c) 2006, Mezimedia. All rights reserved.
*
* @author Yaron Jiang <yjiang@corp.valueclick.com.cn>
* @copyright (C) 2004-2013 Mezimedia.com
* @license http://www.mezimedia.com PHP License 5.0
* @version CVS: $Id: save.phtml,v 1.2 2013/04/18 10:19:33 yjiang Exp $
* @link http://www.dahongbao.com/
* @deprecated File deprecated in Release 3.0.0
*/

$articleForm = $this->articleForm;
?>

<div class="box">
    <div class="box-header">
            <h2><a class="btn btn-inverse" href="<?php echo $this->url('backend' , array('controller' 
            => 'article' , 'action' => 'index'))?>?siteid=<?php echo $articleForm
                ->get('SiteID')->getValue()?>"><i class="icon-white icon-chevron-left"></i>返回列表</a>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <i class="icon-box"></i>编辑文章</h2>
            
    </div>
    
    <div class="box-content">
        <form class="box-form" action="<?php echo $this->url('backend' , array('controller' => 'Article' 
            , 'action' => 'save'))?>?siteid=<?php echo $articleForm->get('SiteID')->getValue()?>" method="post">
            <?php echo $this->formHidden($articleForm->get('ArticleID'))?>
            <?php echo $this->formHidden($articleForm->get('SiteID'))?>
            <?php echo $this->formText($articleForm->get('Title'))?>
            <?php echo $this->formSelect($articleForm->get('CategoryID'))?>
            <?php echo $this->formText($articleForm->get('Keyword'))?>
            <?php echo $this->formTextarea($articleForm->get('Summary'))?>
            <?php echo $this->formTextarea($articleForm->get('Detail'))?>
            <?php echo $this->formSelect($articleForm->get('State'))?>
            <?php echo $this->formText($articleForm->get('Order'))?>
            <?php echo $this->formSubmit($articleForm->get('submit') , '提交')?>
        </form>
    </div>
</div>
<?php 
$this->headScript()->appendFile($this->basePath('editor/editor_config.js'))
->appendFile($this->basePath('editor/editor_all_min.js'))
->appendFile($this->basePath('js/BackEnd/article.js'));
?>