<?php
/**
* index.phtml
*-------------------------
*
* 
*
* PHP versions 5
*
* LICENSE: This source file is from Smarter Ver2.0, which is a comprehensive shopping engine 
* that helps consumers to make smarter buying decisions online. We empower consumers to compare 
* the attributes of over one million products in the common channels and common categories
* and to read user product reviews in order to make informed purchase decisions. Consumers can then 
* research the latest promotional and pricing information on products listed at a wide selection of 
* online merchants, and read user reviews on those merchants.
* The copyrights is reserved by http://www.mezimedia.com. 
* Copyright (c) 2006, Mezimedia. All rights reserved.
*
* @author Yaron Jiang <yjiang@corp.valueclick.com.cn>
* @copyright (C) 2004-2013 Mezimedia.com
* @license http://www.mezimedia.com PHP License 5.0
* @version CVS: $Id: index.phtml,v 1.1 2013/04/15 10:57:15 rock Exp $
* @link http://www.dahongbao.com/
* @deprecated File deprecated in Release 3.0.0
*/
?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>资源列表</h2>
    </div>
    
    <div class="box-content">
    <p>
     <a class="btn btn-success" href="<?php echo $this->url('backend' 
         , array('controller' => 'resource' , 'action' => 'updateResource'));?>">
        <i class="icon-plus"></i>更新资源</a></p>
        <table class="table">
            <thead>
                <tr class="row">
                    <th>资源名</th>
                    <th>控制器名</th>
                    <th>控制器别名</th>
                    <th>动作名</th>
                    <th>动作别名</th>
                    <th>添加时间</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                <?php if(count($this->paginaction) > 0):?>
                <?php foreach($this->paginaction as $resource):?>
                <tr>
                    <td><?php echo $resource->Name?></td>
                    <td><?php echo $resource->Controller?></td>
                    <td><?php echo $resource->ControllerName?></td>
                    <td><?php echo $resource->Action?></td>
                    <td><?php echo $resource->ActionName?></td>
                    <td><?php echo $resource->AddTime?></td>
                    <td>
                        <a class="btn btn-edit" href="<?php echo $this->url('backend' , array('controller' => 'resource' 
                            , 'action' => 'save'))?>?id=<?php echo $resource->ResourceID?>"><i class="icon-edit"></i>
                            设置别名</a>
                            <?php /*
                        <a class="btn btn-delete" href="<?php echo $this->url('backend' , array('controller' => 'resource' 
                            , 'action' => 'delete'))?>?name=<?php echo $resource->Name?>"><i class="icon-delete"></i>
                            删除</a>
                            */?>
                    </td>
                </tr>
                <?php endforeach;?>
                <?php endif;?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link' => $this->url('backend' , array('controller' => 'resource' , 'action' => 'index'))));?>
    </div>
</div>