<?php
/**
 * index.phtml
 * -------------------------
 *
 * 
 *
 * PHP versions 5
 *
 * LICENSE: This source file is from Smarter Ver2.0, which is a comprehensive shopping engine 
 * that helps consumers to make smarter buying decisions online. We empower consumers to compare 
 * the attributes of over one million products in the common channels and common categories
 * and to read user product reviews in order to make informed purchase decisions. Consumers can then 
 * research the latest promotional and pricing information on products listed at a wide selection of 
 * online merchants, and read user reviews on those merchants.
 * The copyrights is reserved by http://www.mezimedia.com. 
 * Copyright (c) 2006, Mezimedia. All rights reserved.
 *
 * @author Yaron Jiang<yjiang@corp.valueclick.com>
 * @copyright (C) 2004-2013 Mezimedia.com
 * @license http://www.mezimedia.com PHP License 5.3
 * @version CVS: $Id: index.phtml,v 1.2 2013/05/10 02:02:31 yjiang Exp $
 * @link http://www.dahongbao.com
 * @deprecated File deprecated in Release 3.0.0
 */
$this->headLink()->prependStylesheet($this->basePath() . '/styles/BackEnd/bootstrap-responsive.min.css')
        ->appendStylesheet($this->basePath() . '/styles/BackEnd/bootstrap-redy.css')
        ->appendStylesheet($this->basePath() . '/styles/BackEnd/charisma-app.css');
        
$this->headScript()->appendFile($this->basePath('js/jquery-1.9.1.min.js'))
->appendFile($this->basePath('js/BackEnd/validator.js'))
->appendFile($this->basePath('js/BackEnd/login.js'));
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="row-fluid">
            <div class="span12 center login-header"><h2>欢迎来到大红包管理后台</h2></div>
        </div>
        <div class="row-fluid">
            <div class="well span3 center login-box">
                <div class="alert alert-info"> 请输入您的用户名和密码。 </div>
                <form class="form-horizontal" method="post" action="<?php echo $this->url('backend' , array('controller' => 'login' , 'action' => 'submit'));?>">
                    <fieldset>
                        <div class="control-group error">
                            <?php if($this->msg):?>
                            <?php foreach($this->msg as $msg):?>
                            <p class="help-block"><i class="icon-warning-sign"></i><?php echo $msg;?></p>
                            <?php endforeach;?>
                            <?php endif;?>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="username">用户:</label>
                            <input class="" type="text" name="username" id="username" />
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="password">密码:</label>
                            <input class="" type="password" name="password" id="password" />
                        </div>
                        <p class="center span3">
                            <button disabled="disabled" name="submit" class="btn btn-primary" type="submit">登录</button>
                        </p>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>