<?php

/**
* basic.phtml
*-------------------------
*
* 
*
* PHP versions 5
*
* LICENSE: This source file is from Smarter Ver2.0, which is a comprehensive shopping engine 
* that helps consumers to make smarter buying decisions online. We empower consumers to compare 
* the attributes of over one million products in the common channels and common categories
* and to read user product reviews in order to make informed purchase decisions. Consumers can then 
* research the latest promotional and pricing information on products listed at a wide selection of 
* online merchants, and read user reviews on those merchants.
* The copyrights is reserved by http://www.mezimedia.com. 
* Copyright (c) 2006, Mezimedia. All rights reserved.
*
* @author Yaron Jiang<yjiang@corp.valueclick.com>
* @copyright (C) 2004-2013 Mezimedia.com
* @license http://www.mezimedia.com PHP License 5.3
* @version CVS: $Id: basic.phtml,v 1.1 2013/04/15 10:57:15 rock Exp $
* @link http://www.dahongbao.com
* @deprecated File deprecated in Release 3.0.0
*/
?>
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php 
            echo $this->headLink(
                            array(
                                'rel' => 'shortcut icon', 
                                'type' => 'image/vnd.microsoft.icon', 
                                'href' => $this->basePath() . '/img/favicon.ico'
                            )
                      )
        ?>

        
    </head>
    <body>
        <?php echo $this->content; ?>
        <!-- Scripts -->
        <?php echo $this->headScript() ?>
    </body>
</html>