<!--html demo-->
<div class="box">
<div class="box-header"><h2><i class="icon-box"></i> Form Elements</h2></div>
<div class="box-content">
<form class="box-form">
    <fieldset>
        <legend>Datepicker, Autocomplete, WYSIWYG</legend>
    </fieldset>
    <div class="input-group">
        <label class="input-label">Auto complete </label>
        <div class="input-item">
            <input class="input-element" type="text">
            <p class="input-help-inline">Start typing to activate auto complete!</p>
            <p class="input-help-block">Start typing to activate auto complete!</p>
        </div>
    </div>
    <div class="input-group">
        <label class="input-label">Auto complete </label>
        <div class="input-item">
            <select  class="input-element select-element">
                <option>Option 1</option>
                <option>Option 2</option>
                <option>Option 3</option>
                <option>Option 4</option>
                <option>Option 5</option>
            </select>
            <p class="input-help-block">Start typing to activate auto complete!</p>
        </div>
    </div>
    
    <div class="button-group">
      <button class="button-element" type="submit">Save changes</button>
      <button class="button-reset" type="reset">Cancel</button>
    </div>
</form>
</div>
</div>

<div class="box">
<div class="box-header"><h2><i class="icon-box"></i> Form Elements</h2></div>
<div class="box-content">

   <div>
   <form class="table-form-filter">
   <div class="input-filter">
        <label>
        <select class="select-element">
            <option value="10" selected="selected">10</option>
            <option value="25">25</option><option value="50">50</option>
            <option value="100">100</option>
        </select> records per page
        </label>
   </div>
    
   <div class="input-filter">
    <label>Search: <input type="text" class="input-element"></label>
   </div>
   </form>

   </div>
   <table class="table">
  <thead>
      <tr class="row">
      <th rowspan="1" colspan="1" style="width: 118px;">Username</th>
      <th rowspan="1" colspan="1" style="width: 105px;">Date registered</th>
      <th rowspan="1" colspan="1" style="width: 52px;">Role</th>
      <th rowspan="1" colspan="1" style="width: 48px;">Status</th>
      <th rowspan="1" colspan="1" style="width: 102px;">Actions</th></tr>
  </thead>
  <tbody role="alert" aria-live="polite" aria-relevant="all">
    <tr class="odd">
        <td class="  sorting_1">Abdullah</td>
        <td class="center ">2012/02/01</td>
        <td class="center ">Staff</td>
        <td class="center ">
            <span class="active-status">Active</span>
        </td>
        <td class="center">
            <a href="#" class="btn btn-view"><i class="icon-view icon-white"></i>View</a>
            <a href="#" class="btn btn-edit"><i class="icon-edit icon-white"></i>  Edit</a>
            <a href="#" class="btn btn-delete"><i class="icon-delete icon-white"></i> Delete</a>
        </td>
    </tr>
    <tr>
        <td class="  sorting_1">Abdullah</td>
        <td class="center ">2012/02/01</td>
        <td class="center ">Staff</td>
        <td class="center ">
            <span class="banned-status">Banned</span>
        </td>
        <td class="center ">
            <a href="#" class="btn btn-view"><i class="icon-view icon-white"></i>View</a>
            <a href="#" class="btn btn-edit"><i class="icon-edit icon-white"></i>  Edit</a>
            <a href="#" class="btn btn-delete"><i class="icon-delete icon-white"></i> Delete</a>
        </td>
    </tr>
    <tr>
        <td class="  sorting_1">Abdullah</td>
        <td class="center ">2012/02/01</td>
        <td class="center ">Staff</td>
        <td class="center ">
            <span class="banned-status">Banned</span>
        </td>
        <td class="center ">
            <a href="#" class="btn btn-view"><i class="icon-view icon-white"></i>View</a>
            <a href="#" class="btn btn-edit"><i class="icon-edit icon-white"></i>  Edit</a>
            <a href="#" class="btn btn-delete"><i class="icon-delete icon-white"></i> Delete</a>
        </td>
    </tr>
    <tr>
        <td class="  sorting_1">Abdullah</td>
        <td class="center ">2012/02/01</td>
        <td class="center ">Staff</td>
        <td class="center ">
            <span class="banned-status">Banned</span>
        </td>
        <td class="center ">
            <a href="#" class="btn btn-view"><i class="icon-view icon-white"></i>View</a>
            <a href="#" class="btn btn-edit"><i class="icon-edit icon-white"></i>  Edit</a>
            <a href="#" class="btn btn-delete"><i class="icon-delete icon-white"></i> Delete</a>
        </td>
    </tr>
    <tr>
        <td class="  sorting_1">Abdullah</td>
        <td class="center ">2012/02/01</td>
        <td class="center ">Staff</td>
        <td class="center ">
            <span class="banned-status">Banned</span>
        </td>
        <td class="center ">
            <a href="#" class="btn btn-view"><i class="icon-view icon-white"></i>View</a>
            <a href="#" class="btn btn-edit"><i class="icon-edit icon-white"></i>  Edit</a>
            <a href="#" class="btn btn-delete"><i class="icon-delete icon-white"></i> Delete</a>
        </td>
    </tr>
  </tbody>
   </table>

   <div class="pagination">
    <ul>
        <li class="prev disabled">
            <a href="#">← Previous</a>
        </li>
        <li class="active"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li class="next"><a href="#">Next → </a></li>
     </ul>
   </div>

</div>
</div>