<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('大红包后台管理系统')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php 
            echo $this->headLink(
                            array(
                                'rel' => 'shortcut icon', 
                                'type' => 'image/vnd.microsoft.icon', 
                                'href' => $this->basePath() . '/img/favicon.ico'
                            )
                      )
                      ->prependStylesheet($this->basePath() . '/styles/BackEnd/style.css')
                      ->prependStylesheet($this->basePath() . '/styles/BackEnd/comm.css');
        ?>
        
        <!-- Scripts -->
       <?php
        echo $this->headScript()->prependFile($this->basePath('js/BackEnd/comm.js'))
            ->prependFile($this->basePath('js/BackEnd/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-1.9.1.min.js'));
       ?>
        
    </head>
    <body>
       <?php print $this->partial('layout/header.phtml'); ?>
       <div class="wrapper">
        <div class="main">
            <?php echo $this->mynavigation('backendNav')->menu()->setPartial('layout/leftSideBar.phtml'); ?>
            <!-- main left end -->
            <div class="colMain">
            <?php if(!empty($this->flashMessage['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($this->flashMessage['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($this->flashMessage['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($this->flashMessage['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
                <?php echo $this->mynavigation('backendNav')->breadcrumbs()->setPartial('layout/breadcrumb.phtml');?>
                <!-- breadcrumb -->
                <?php echo $this->content; ?>
            </div>
        </div>
        <!--main end-->

        </div>
        <!--wrapper end-->
        <hr>
        <?php print $this->partial('layout/footer.phtml'); ?>
        <!--footer end-->
        
       </div>
       <!--wrapper end-->
    </body>
</html>
