<?php if ($this->pageCount > 1): ?>
<?php 
    if(strrpos($this->link , '?') === false){
        $prefix = '?page=';
    }else{
        $prefix = '&page=';
    }
?>
<div class="pagination">
    <ul>
        <?php if (isset($this->previous)): ?>
        <li class="prev disabled">
            <a href="<?php echo $this->link . $prefix . $this->previous;?>">上一页</a>
        </li>
        <?php endif;?>
        <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li><a href="<?php echo $this->link . $prefix . $page;?>"><?php echo $page; ?></a></li>
            
        <?php else:?>
            <li class="active"><a href="#"><?php echo $page; ?></a></li>
        <?php endif;?>
        <?php endforeach;?>
        <?php if (isset($this->next)): ?>
        <li class="next"><a href="<?php echo $this->link . $prefix . $this->next;?>">下一页</a></li>
        <?php endif;?>
     </ul>
</div>
<?php endif;?>