<?php
/**
* index.phtml
*-------------------------
*
* 
*
* PHP versions 5
*
* LICENSE: This source file is from Smarter Ver2.0, which is a comprehensive shopping engine 
* that helps consumers to make smarter buying decisions online. We empower consumers to compare 
* the attributes of over one million products in the common channels and common categories
* and to read user product reviews in order to make informed purchase decisions. Consumers can then 
* research the latest promotional and pricing information on products listed at a wide selection of 
* online merchants, and read user reviews on those merchants.
* The copyrights is reserved by http://www.mezimedia.com. 
* Copyright (c) 2006, Mezimedia. All rights reserved.
*
* @author Yaron Jiang <yjiang@corp.valueclick.com.cn>
* @copyright (C) 2004-2013 Mezimedia.com
* @license http://www.mezimedia.com PHP License 5.0
* @version CVS: $Id: index.phtml,v 1.2 2013/04/18 09:17:08 yjiang Exp $
* @link http://www.dahongbao.com/
* @deprecated File deprecated in Release 3.0.0
*/
$this->headScript()->appendFile($this->basePath('js/BackEnd/article-category-index.js'));

$list = new RecursiveIteratorIterator($this->list, RecursiveIteratorIterator::SELF_FIRST);
?>

<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>文章分类管理</h2>
    </div>
    
    <div class="box-content">
    <div class="input-group"><a class="btn btn-success" href="<?php echo $this->url('backend' , array('controller' => 'ArticleCategory' 
        , 'action' => 'save'))?>?siteid=<?php echo $this->SiteID?>"><i class="icon-plus"></i>增加分类</a></div>
            <select id="siteid" class="select-element input-element span2"" name="SiteID">
                <?php foreach($this->sites as $k => $v):?>
                <option <?php if($k == $this->SiteID):?>
                    selected="selected"<?php endif;?> value="<?php echo 
                    $this->url('backend' , array('controller'
                        => 'articleCategory' , 'action' 
                        => 'index'))?>?SiteID=<?php echo $k?>"><?php echo $v?></option>
                <?php endforeach;?>
            </select>
    </div>
    
    <?php if($this->list):?>
        <table class="table">
        <thead>
            <tr class="row">
                <th>分类名</th>
                <th>显示名</th>
                <th>文章数</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach($list as $v):
            ?>
            <?php 
                $count = isset($this->articleCount[$v->CategoryID])? $this->articleCount[$v->CategoryID] : 0;
                $depth = $list->getDepth();
                $myDepth = '';
                if($depth > 0){
                    $myDepth = str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $depth);
                    $myDepth .= '├----' ;
                }
            ?>
            <tr class="row">
                <td><?php echo $myDepth . $v->Name;?></td>
                <td><?php echo $v->CnName?></td>
                <td>
                <a href="<?php echo $this->url(null , array('controller' => 'article'));
                ?>?CategoryID=<?php echo $v->CategoryID?>"><?php echo $count?></a>
                </td>
                <td>
                    <a class="btn btn-edit" href="<?php echo $this->url('backend' 
                        , array('controller' => 'ArticleCategory' , 'action' => 'save'))?>?id=<?php echo $v
                            ->CategoryID?>&siteid=<?php echo $this->SiteID?>">编辑</a>
                            <?php if($count < 1):?>
                    <a class="btn btn-delete" href="<?php echo $this->url('backend' 
                        , array('controller' => 'ArticleCategory' , 'action' => 'delete'))?>?id=<?php echo $v
                            ->CategoryID?>">删除</a>
                            <?php endif;?>
                            
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
        </table>
    <?php endif;?>
    </div>
</div>