<?php
/**
* index.phtml
*-------------------------
*
* 
*
* PHP versions 5
*
* LICENSE: This source file is from Smarter Ver2.0, which is a comprehensive shopping engine 
* that helps consumers to make smarter buying decisions online. We empower consumers to compare 
* the attributes of over one million products in the common channels and common categories
* and to read user product reviews in order to make informed purchase decisions. Consumers can then 
* research the latest promotional and pricing information on products listed at a wide selection of 
* online merchants, and read user reviews on those merchants.
* The copyrights is reserved by http://www.mezimedia.com. 
* Copyright (c) 2006, Mezimedia. All rights reserved.
*
* @author Yaron Jiang <yjiang@corp.valueclick.com.cn>
* @copyright (C) 2004-2013 Mezimedia.com
* @license http://www.mezimedia.com PHP License 5.0
* @version CVS: $Id: index.phtml,v 1.3 2013/04/18 09:17:07 yjiang Exp $
* @link http://www.dahongbao.com/
* @deprecated File deprecated in Release 3.0.0
*/
$this->headScript()->appendFile($this->basePath('js/BackEnd/merchant-index.js'));
?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>商家管理</h2>
    </div>
    
    <div class="box-content">
    
    <div class="form-inline">
    <div class="input-group">
        <a href="<?php echo $this->url('backend' , array('controller' => 'merchant' , 'action' => 'save'))
        ?>?SiteId=<?php echo $this->SiteId?>&referer=<?php echo $this->uri?>"
         class="btn btn-success">添加商家</a>
    </div>
        <form class="box-form" action="<?php $this->url('backend' , array('controller' 
            => 'merchant' , 'action' => 'index'))?>"
            method="get">
            <div class="input-group">
                <select class="select-element input-element span2" id="sites" name="SiteId">
                    <?php foreach($this->sites as $k => $v):?>
                    <option value="<?php echo $k?>" <?php if($k == $this->SiteId):?>selected="selected"<?php endif;?>>
                    <?php echo $v?>
                    </option>
                    <?php endforeach;?>
                </select>
                &nbsp;&nbsp;
                
                <label class="">分类:</label>
                <select class="select-element input-element span2" name="CategoryID">
                    <option value="">所有</option>
                    <?php foreach($this->categories as $k => $v):?>
                    <option <?php if($k == $this->CategoryID):?>
                        selected="selected"<?php endif;?> value="<?php echo $k?>"><?php echo $v?></option>
                    <?php endforeach;?>
                </select>
                &nbsp;&nbsp;
                <label class="">Affiliate:</label>
                <select class="select-element input-element span2" name="AffiliateID">
                    <option value="">所有</option>
                    <?php foreach($this->affilites as $k => $v):?>
                    <option value="<?php echo $k?>" <?php if($k == $this->AffiliateID):?>selected="selected"<?php endif;?> >
                    <?php echo $v?>
                    </option>
                    <?php endforeach;?>
                </select>
                &nbsp;&nbsp;
            
                <select class="select-element input-element span2" name="IsActive">
                    <option <?php if('YES' == $this->IsActive):?>selected="selected"
                        <?php endif;?> value="YES">在线商家</option>
                    <option <?php if('NO' == $this->IsActive):?>selected="selected"
                        <?php endif;?> value="NO">下线商家</option>
                </select>
                
            </div>
            <div class="input-group">
            <select name="searchType" class="select-element input-element span2">
                    <option value="id" <?php if('id' == $this->searchType):?>selected="selected"<?php endif;?>>商家ID
                    </option>
                    <option <?php if('name' == $this->searchType):?>selected="selected"<?php endif;?> value="name">
                    商家名</option>
                </select>
                <input name="search" type="text" class="input-element" placeholder="搜索商家" value="<?php echo 
         $this->escapeHtml($this->search)?>" />
                </div>
                
                <button class="btn btn-primary" type="submit">搜索</button>
                
                <a class="btn btn-inverse" href="<?php echo $this->url('backend' , array('controller' 
                    => 'merchant' , 'action' => 'index'))?>?siteid=1">清除条件</a>
            </div>
            
        </form>
        </div>
        <form class="form" method="post" action="
        <?php if($this->IsActive == 'YES'):?>
        <?php echo $this->url('backend' , array('controller' => 'merchant' , 'action' => 'inactive'))?>
        <?php else:?>
        <?php echo $this->url('backend' , array('controller' => 'merchant' , 'action' => 'active'))?>
        <?php endif;?>
        ">
            <?php if(!empty($this->merchants)):?>
            <table class="table">
                <thead>
                    <tr class="row">
                    <th width="12"><input type="checkbox" id="allCheck" /></th>
                    <th width="36">ID</th>
                    <th>商家名</th>
                    <th>Affiliate</th>
                    <th>Coupons</th>
                    <th>排序</th>
                    <th width="160">操作</th>
                    </tr>
                </thead>
                
                <tbody>
                    <?php foreach($this->merchants as $k => $v):?>
                        <tr class="row">
                            <td>
                                <input type="checkbox" name="MerchantID[]" value="<?php echo $k?>" />
                            </td>
                            
                            <td>
                                <?php echo $k?>
                            </td>
                            
                            
                            <td>
                                <?php echo $v['MerchantName']?>
                            </td>
                            
                            <td>
                                <?php echo !empty($v['AffiliateID']) ? 
                                    isset($this->affilites[$v['AffiliateID']])?
                                 $this->affilites[$v['AffiliateID']]:'无' : '无';?>
                            </td>
                            
                            <td>
                            <?php if($v['CouponCount'] > 0):?>
                                <a href="<?php echo $this->url(null , array('controller' => 'coupon' , 'action' => 
                                    'couponList'))?>?MerchantSearchType=MerchantID&MerchantSearch=<?php echo $k
                                ?>"><?php echo $v['CouponCount']?></a>
                                <?php else:?>
                                <?php echo $v['CouponCount']?>
                                <?php endif;?>
                            </td>
                            
                            <td>
                                <?php echo $v['Sequence']?>
                            </td>
                            
                            <td>
                            <div class="btn-group">
                                <?php if($this->IsActive == 'YES'):?>
                                <a class="btn btn-inverse" href="<?php echo $this->url('backend' , array('controller' 
                                    => 'merchant' 
                                    , 'action' => 'inactive'))?>?MerchantID=<?php echo $k?>">
                                    
                                    下线</a>
                                <?php else:?>
                                <a class="btn btn-inverse" href="<?php echo $this->url('backend' , array('controller' 
                                    => 'merchant' , 'action' => 'active'))?>?MerchantID=<?php echo $k?>">
                                    上线</a>
                                <?php endif;?>
                                
                                <a class="btn btn-edit" href="<?php echo $this->url('backend' , array('controller' 
                                    => 'merchant' , 'action' => 'save'))?>?SiteId=<?php echo $this
                                ->SiteId?>&id=<?php echo $k?>&referer=<?php echo $this->uri
                                ?>">编辑</a>
                                <a class="btn btn-success" href="<?php echo $this->url(null , array('controller' => 'recommend' , 'action' => 'save'))?>?ID=<?php 
echo $k?>&ContentType=MERCHANT&SiteID=<?php echo $this->SiteId?>&referer=<?php echo $this->uri?>">推荐</a>
                                <?php /*
                                <a class="btn btn-delete" href="<?php echo $this->url('backend' , array('controller' 
                                    => 'merchant' , 'action' => 'delete'))?>?SiteId<?php echo $this
                                ->SiteId?>&id=<?php echo $k?>"><i class="icon-white icon-delete"></i>删除</a> 
                                */?>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach;?>
                </tbody>
                
                <tfoot>
                <tr>
                <td colspan=7><?php echo $this->paginationControl($this->paginator,'Sliding','layout/pagination' 
                         , array('link' => $this->url('backend' , array('controller' 
                        => 'merchant' , 'action' => 'index')) . '?' . $this->query));?></td>
                     </tr>
                     
                <tr>
                    <td colspan=7>
                    <?php if($this->IsActive == 'YES'):?>
                        <button class="btn btn-delete">下线</button>
                        <?php else:?>
                        <button class="btn btn-success">上线</button>
                        <?php endif;?>
                    </td>
                </tr>
                </tfoot>
            </table>
            <?php else:?>
            <p>没有数据</p>
            <?php endif;?>
        </form>
    </div>
</div>